// Generated by LiveScript 1.5.0
var m, App, Home;
m = require('mithril');
App = require('../components/app');
Home = {};
Home.view = function(){
  return m.component(App, m('#home-view', 'nice!'));
};
module.exports = Home;