// Generated by LiveScript 1.5.0
var m, App, SearchComp, Settings;
m = require('mithril');
App = require('../components/app');
SearchComp = require('../components/search');
Settings = {};
Settings.view = function(){
  return m.component(App, m('#settings-view', [SearchComp]));
};
module.exports = Settings;