// Generated by LiveScript 1.5.0
var m, App, Settings;
m = require('mithril');
App = require('../components/app');
Settings = {};
Settings.view = function(){
  return m.component(App, m('#settings-view', 'settings'));
};
module.exports = Settings;