// Generated by LiveScript 1.5.0
var routes, utils, m;
routes = require('../routes');
utils = {};
m = require('mithril');
utils.getCurrentRoute = function(){
  var foundRoute;
  foundRoute = {};
  routes.forEach(function(route){
    if (route.url.href === m.route()) {
      return foundRoute = route;
    }
  });
  return foundRoute;
};
utils.getCurrentRouteIndex = function(){
  var index;
  index = 0;
  routes.forEach(function(route, i){
    if (route.url.href === m.route()) {
      return index = i;
    }
  });
  return index;
};
module.exports = utils;