// Generated by LiveScript 1.5.0
var m, search, iconButton, iconSearch, iconBack, iconClear, shadow, btnSearch, btnDismiss, btnClear, Search;
m = require('mithril');
search = require('polythene/search/search');
iconButton = require('polythene/icon-button/icon-button');
iconSearch = require('mmsvg/google/msvg/action/search');
iconBack = require('mmsvg/google/msvg/navigation/arrow-back');
iconClear = require('mmsvg/google/msvg/content/clear');
shadow = require('polythene/shadow/shadow');
btnSearch = m.component(iconButton, {
  icon: {
    msvg: iconSearch
  }
});
btnDismiss = m.component(iconButton, {
  icon: {
    msvg: iconBack
  }
});
btnClear = function(ctrl){
  return m.component(iconButton, {
    icon: {
      msvg: iconClear
    },
    events: {
      onclick: function(){
        ctrl.query().value = '';
        m.redraw();
        ctrl.query().el.focus();
      }
    }
  });
};
Search = {};
Search.controller = function(){
  return {
    query: m.prop()
  };
};
Search.view = function(ctrl){
  return m('.search-component', m.component(search, {
    type: 'fullwidth',
    textfield: {
      label: 'Search',
      value: function(){
        var ref$;
        return ((ref$ = ctrl.query()) != null ? ref$.value : void 8) || '';
      },
      getState: ctrl.query
    },
    buttons: {
      none: {
        before: btnSearch
      },
      focus: {
        before: btnSearch
      },
      focus_dirty: {
        before: btnDismiss,
        after: btnClear(ctrl)
      },
      dirty: {
        before: btnDismiss
      }
    },
    before: m.component(shadow)
  }));
};
module.exports = Search;